Add encoding module with a simple encoder
HerySon/teaching_ML_project pull request #3
Opened 2022-01-21 18:45 UTC by baptistesauvecanne

2022-01-24 14:35 UTC, RisbourgNathan commented on scripts/encoding/encoder.py
> +    'vect': CountVectorizer()
Pas la peine d'instancier, on ne sait pas encore quel encodeur on va utiliser
```suggestion
    'tfidf': TfidfVectorizer,
    'vect': CountVectorizer
```

2022-01-24 15:22 UTC, RisbourgNathan commented on scripts/encoding/encoder.py
> +ENCODER_TOOLS = {
Les autres modules auront probablement pas besoin d'utiliser cette constante (privée au package), on peut ajouter un underscore pour le montrer. (Penser à modifier le reste du fichier)
```suggestion
_ENCODER_TOOLS = {
```

2022-01-24 16:03 UTC, RisbourgNathan commented on scripts/encoding/encoder.py
> +    df_vectorized = pd.DataFrame()
Plutôt que de récupérer un subset du DataFrame puis d'en créer un neuf, on peut directement faire une copie du subset

2022-01-24 16:06 UTC, RisbourgNathan commented on scripts/encoding/encoder.py
> +        df_vectorized[column] = x.toarray()
Je sais pas exactement quel résultat on attend en sortie mais sur le dataset de 4Go le _toarray()_ tente d'allouer plusieurs dizaines de téras d'un seul coup

2022-01-25 14:11 UTC, HerySon commented on scripts/encoding/encoder.py
> +        df_vectorized[column] = x.toarray()
Il faut eviter de stocker le resultat des features vectorisées sous forme d'array, car cela consomme beaucoup de RAM. Il faut rester avec le format de [sparse matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) renvoyé par défaut qui consomme moins de mémoire

2022-01-25 14:18 UTC, HerySon commented on scripts/encoding/encoder.py
> +    'vect': CountVectorizer()
Ca n'est pas une modification prioritaire mais elle peut être bienvenue. Attention à ne pas oublier de changer l'appel du vectoriser à la ligne 24

2022-01-25 14:18 UTC, HerySon commented on scripts/encoding/encoder.py
> +    df_vectorized = pd.DataFrame()
Ca n'est pas une modification prioritaire mais elle peut être bienvenue

2022-01-25 14:44 UTC, HerySon commented
@baptistesauvecanne Tu as utilisé du code pour vectoriser des features textuelles, dont le but est de les ré-encoder en comptant la fréquence d'apparition des mots dans un corpus de texte, ce qui n'était pas l'objet (principal) de la tâche. Ce comportement peut être utile pour certaines features comme _ingredients_text_
Pourrais-tu :
- [ ] rajouter du code pour encoder  les features catégorielles numériques plus "classiques" (comme par ex countries, stores, ...) avec un OneHotEncoder
- [ ] modifier la fonction pour appliquer différents encoder en fonction du type de colonne à encoder
- [ ] renvoyer le dataframe d'origine avec les features encodées à la place des features originelles, plutôt que de ne renvoyer que le subset des colonnes ré-encodées ?

Tu peux t'inspirer du code de @RisbourgNathan dans /preprocessing/scaling/scaling.py

2022-01-25 19:54 UTC, baptistesauvecanne commented on scripts/encoding/encoder.py
> +    'vect': CountVectorizer()
L'idée est que la personne faisant le preprocessing puissent avoir le choix de changer d'encodeur pour x ou y raison sur quelques colonnes, etc...

2022-01-25 20:05 UTC, RisbourgNathan commented on scripts/encoding/encoder.py
> +    'vect': CountVectorizer()
Je comprends mais autant avoir un dictionnaire de classes qu'on instancie quand on décide de s'en servir plutôt qu'un dictionnaire d'objets. C'est pas dramatique mais c'est toujours quelques cycles CPU en moins

2022-01-25 20:05 UTC, baptistesauvecanne commented
@HerySon je suis parti de son dont on avait évoqué vendredi, après j'ai du mal comprendre. Mais je ferais les modifications nécessaire. 

1. Ok je vais rajouter pour prendre en compte le OneHotEncoder. 
2. C'est se dont j'ai prévu initialement dans ce module. L'idée est de pouvoir avoir à disposition un dictionnaire d'outil est de les utilisés à souhait sur différents subset du Dataframe. 
3. Pour moi il me semble qu'il serait judicieux de garder une structure modulable, il prend en entrée un Dataframe contenant les colonnes sélectionnés par la partie preprocessing et en sortie le même Dataframe avec les features encodés.

2022-01-25 20:16 UTC, RisbourgNathan commented
>     3. Pour moi il me semble qu'il serait judicieux de garder une structure modulable, il prend en entrée un Dataframe contenant les colonnes sélectionnés par la partie preprocessing et en sortie le même Dataframe avec les features encodés.

@baptistesauvecanne  Je pense que c'est ce qu' @HerySon propose mais dans ton code tu renvoies un subset du DataFrame que tu reçois. Idéalement tu ne devrais pas avoir besoin de renvoyer quelque chose car le DataFrame est mutable dans une fonction. 
Si tu veux vraiment renvoyer un subset, pense à utiliser la méthode copy pour éviter de créer des vues et d'avoir des mauvaises surprises plus tard.

(Je me permets d'écrire des commentaires mais c'est histoire d'en discuter, c'est juste mon avis évidemment)

2022-01-26 12:22 UTC, HerySon commented
@baptistesauvecanne Pour clarifier la question sur le 3., il est plus courant et facile d'utilisation de remplacer les colonnes re-encodées par celle originales, sans perte de modularité (plutôt que de ne renvoyer qu'un subset du dataframe). Comme le  précise @RisbourgNathan le dataframe est mutable et tu peux y appliquer directement le résultat de tes traitements. Tu peux t'inspirer de ce qu'il a fait

2022-01-28 17:37 UTC, baptistesauvecanne commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Tache1.1][3pts] Encoder les features non numériques](https://trello.com/c/2d5nSSsV/3-tache113pts-encoder-les-features-non-num%C3%A9riques)

2022-01-28 18:41 UTC, RisbourgNathan commented
Pas bête d'utiliser le module logging plutôt que des print

2022-01-28 20:03 UTC, RisbourgNathan requested changes

2022-01-28 20:03 UTC, RisbourgNathan commented on scripts/preprocessing/encoding/encoding.py
> +        logging.warning("Encoder tool doesn't exist or is not supported, automatically switch to OneHotEncoder")
Tu n'utilises _use_encoder_ nulle part.

```suggestion
    if encoder is None or encoder not in _ENCODER_TOOLS:
        encoder = 'OneHotEncoder'
        logging.warning("Encoder tool doesn't exist or is not supported, automatically switch to OneHotEncoder")
```

2022-01-30 20:41 UTC, baptistesauvecanne commented on scripts/preprocessing/encoding/encoding.py
> +        exit()
Je vais modifier

2022-02-02 09:50 UTC, baptistesauvecanne reviewed
Bien vu des fautes inadvertence ! ;-)

2022-02-02 17:20 UTC, merged